# Generated by Django 6.0 on 2026-08-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='seller', max_length=10),
        ),
    ]
