# Generated by Django 6.0 on 2026-08-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('employer', 'Employer')], default='seller', max_length=10),
        ),
    ]
