# Generated by Django 6.0 on 2026-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_sellerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('seller', 'Seller'), ('employer', 'Employer')], default='user', max_length=10),
        ),
    ]
