# Generated by Django 6.0 on 2026-08-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
