# Generated by Django 6.0.5 on 2026-09-30 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_cart_order_orderitem_inventoryreservation_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfilment_status'], name='orderitem_fulfil_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['dispatched_at'], name='orderitem_dispatched_at_idx'),
        ),
    ]
