# Generated by Django 6.0.5 on 2026-09-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_orderitem_completed_at_orderitem_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.orderitem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.transaction'),
        ),
    ]
