# Generated by Django 6.0.5 on 2026-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_alter_orderitem_fulfilment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pricing_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('for_sale', 'For sale'), ('per_service', 'Per service'), ('per_day', 'Per day'), ('per_week', 'Per week'), ('per_month', 'Per month'), ('per_year', 'Per year')], default='one_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('property', 'Property'), ('fashion', 'Fashion'), ('services', 'Services'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=50),
        ),
    ]
