# Generated by Django 6.0.5 on 2026-10-02 03:42

from django.db import migrations, models


def migrate_listing_categories(apps, schema_editor):
    Listing = apps.get_model("marketplace", "Listing")

    category_mapping = {
        "electronics": "electronics_appliances",
        "property": "property_land",
        "furniture": "home_garden",
    }

    for old_category, new_category in category_mapping.items():
        Listing.objects.filter(category=old_category).update(
            category=new_category
        )


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0023_listing_pricing_type_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("property_land", "Property & Land"),
                    ("vehicles", "Vehicles"),
                    ("phones_tablets", "Phones & Tablets"),
                    ("computers_office", "Computers & Office"),
                    ("electronics_appliances", "Electronics & Appliances"),
                    ("home_garden", "Home & Garden"),
                    ("fashion", "Fashion"),
                    ("baby_kids", "Baby & Kids"),
                    ("health_beauty", "Health & Beauty"),
                    ("sports_fitness", "Sports & Fitness"),
                    ("business_industrial", "Business & Industrial"),
                    ("education", "Education"),
                    ("food_agriculture", "Food & Agriculture"),
                    ("services", "Services"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(
            migrate_listing_categories,
            migrations.RunPython.noop,
        ),
    ]
